In [24]:
from sklearn.naive_bayes import GaussianNB
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder


In [25]:
data=pd.read_excel("data.xls");


In [26]:
x=np.array(data[["Outlook","Temperature","Humidity","Windy"]].values)

encoder = OrdinalEncoder()
encoder.fit(x)
x = encoder.transform(x)
print(x)



[[2. 1. 0. 1.]
 [2. 1. 0. 0.]
 [0. 1. 0. 1.]
 [1. 2. 0. 1.]
 [1. 0. 1. 1.]
 [1. 0. 1. 0.]
 [0. 0. 1. 0.]
 [2. 2. 0. 1.]
 [1. 0. 1. 1.]
 [1. 2. 1. 1.]
 [2. 2. 1. 0.]
 [0. 2. 0. 0.]
 [0. 1. 1. 1.]
 [1. 2. 0. 0.]]


In [32]:
y=np.array(data[["PlayGolf"]].values);

encodery = OrdinalEncoder()
encodery.fit(y)
y= encodery.transform(y)
y=y.ravel()
estimator=GaussianNB();
print(y)
estimator.fit(x,y);

[0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0.]


In [37]:
estimator.predict([[2. ,1., 0., 1.]])


array([0.])